//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfessorSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professor
    {
        public int IdProfessor { get; set; }
        public string Nome { get; set; }
        public string AreaAtuacao { get; set; }
        public string Especialidade { get; set; }
        public Nullable<int> TitulacaoID { get; set; }

        public virtual Titulacao Titulacao { get; set; }
    }
}
